license-key: 'here'

team-info-view:

  name: "ᴛᴇᴀᴍ (Page 1/1)"

  layout:
    - "OOOOOOOOO"
    - "OOOOOOOOO"
    - "OOOOOOOOO"
    - "OOOOOOOOO"
    - "OOOOOOOOO"
    - "XXX<X>XXX"

  teammate-slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44]

  icons:

    invite:
      material: GRAY_STAINED_GLASS_PANE
      name: "#34eb9bɪɴᴠɪᴛᴇ"

    search:
      material: OAK_SIGN
      name: "#34eb9bꜱᴇᴀʀᴄʜ"
      slot: 45

    back:
      material: ARROW
      name: "#34eb9bʙᴀᴄᴋ"

    next:
      material: ARROW
      name: "#34eb9bɴᴇxᴛ"

    team-home:
      material: WHITE_BANNER
      name: "#34eb9bᴛᴇᴀᴍ ʜᴏᴍᴇ"
      slot: 52

    sort-join-date:
      material: HOPPER
      name: "#34eb9bSort (Join Date)"
      slot: 46

    sort-alphabetically:
      material: HOPPER
      name: "#34eb9bSort (Alphabetically)"
      slot: 46

    sort-permissions:
      material: HOPPER
      name: "#34eb9bSort (Permissions)"
      slot: 46

    sort-money:
      material: HOPPER
      name: "#34eb9bSort (Money)"
      slot: 46

    team:
      material: IRON_HELMET
      name: "#34eb9bᴛᴇᴀᴍ %name%"
      lore:
        - '§fClick to refresh'
      slot: 49

    pvp-on:
      material: DIAMOND_SWORD
      name: "#34eb9bᴘᴠᴘ ON"
      slot: 53

    pvp-off:
      material: DIAMOND_SWORD
      name: "#34eb9bᴘᴠᴘ OFF"
      slot: 53

confirm-team-disband-view:

  name: "ᴄᴏɴғɪʀᴍ ᴅɪsʙᴀɴᴅɪɴɢ ᴛᴇᴀᴍ"
  rows: 3

  icons:

    decline:
      material: RED_STAINED_GLASS_PANE
      name: "#e00202ᴄᴀɴᴄᴇʟ"
      lore: "§fClick to cancel"
      slot: 11

    accept:
      material: LIME_STAINED_GLASS_PANE
      name: "#02de4fᴄᴏɴғɪʀᴍ"
      lore: "§fClick to delete"
      slot: 15

messages:
  teleport-move-cancel: '§cThe teleport was cancelled because you moved.'
  teleport-home-success: '§7You teleported to your home'

  teleporting-pending: '§7Teleporting in §b%seconds% §7seconds'

  no-team: '§cYou don''t have a team. Type /team create (name) to create a team.'
  team-no-exist: '§cYour team doesn''t exist. Please contact an administrator.'

  team-taken-name: '§cYou cannot create a team with this name, it is already taken.'
  do-not-have-team: '§cYou do not have a team.'

  team-created: '§aTeam created.'

  already-have-team: '§cYou already have a team.'
  no-pending-invite: '§cYou don''t have a pending invite.'

  joined-team: '§7You joined the team.'
  no-leader: '§cYou are not the team leader.'

  team-no-home: '§7Your team does not have a home.'
  team-home-deleted: '§7Team home deleted.'

  no-permission-command: '§cYou don''t have permission to use this command.'
  player-not-found: '§cPlayer not found.'

  user-not-exist: '§cUser/team does not exist.'
  user-has-pending-invite: '§cUser already has a pending invite.'

  invite-receive: '§7You have been invited to join the team %team%. Type /team join %inviter% to accept.'
  invite-sent: '§7Invite sent.'

  user-not-in-team: '§cUser does not seem to be in your team.'
  user-kicked-from-team: '§7User kicked from the team.'
  team-left: '§7You left the team.'

  home-blocked-region: '§cYou cannot set homes on this region.'
  team-home-set: '§7Team home set.'

  search-name: '§7Type team member name to search'
  wait-to-confirm: '§cWait 1 second before confirming this, are you sure this is not a mistake?'
  disband-team: '§7You disbanded your team'

  team-invite-usage: '§7Type /team invite (name) to invite a player'
  cannot-modify-leader: '§cYou cannot manage the team leader permissions.'